use Cwd;
$username = 'root';
$password = 'northy';
$db_hostname = 'localhost';
$network = '127.0.0.1';
$community_string = 'public';
$db_name = 'erg_diax';
$probe_time = 36;
$path = Cwd::realpath();
$graph_path = $path.'/graphs';
